port/wasm/proto-explorer: fix Uint8Array to binary String conversion
While the spread operator works well for shortish buffers, really long buffers
would cause

  RangeError: Maximum call stack size exceeded